server:
  port: 10011
spring:
  application:
    name: leyou-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jianghu2333/leyou-config-master.git
  rabbitmq:
    host: cd.laiqio.site
    username: admin
    password: admin
    virtual-host: /


management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
